# Generated by Django 4.0.1 on 2022-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
                ('video', models.FileField(upload_to='2022-01-30/')),
            ],
        ),
    ]
