# Generated by Django 4.0.1 on 2022-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosave',
            name='video',
            field=models.ImageField(default='21_36.mp4', upload_to='2022-01-30/'),
        ),
    ]
