# Generated by Django 4.0.1 on 2022-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0002_alter_videosave_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosave',
            name='video',
            field=models.ImageField(default='22_42.mp4', upload_to='<built-in method date of datetime.datetime object at 0x0000020EA416B0F0>/'),
        ),
    ]
