# Generated by Django 4.0.1 on 2022-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0003_alter_videosave_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosave',
            name='subject',
        ),
        migrations.AlterField(
            model_name='videosave',
            name='video',
            field=models.ImageField(default='0_24.mp4', upload_to='<built-in method date of datetime.datetime object at 0x000002856E18D0F0>/'),
        ),
    ]
