# Generated by Django 3.1.3 on 2022-02-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0004_remove_videosave_subject_alter_videosave_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosave',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videosave',
            name='video',
            field=models.ImageField(default='10_48.mp4', upload_to='<built-in method date of datetime.datetime object at 0x0000024C63E56F10>/'),
        ),
    ]
