# Generated by Django 4.0.1 on 2022-02-04 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0005_auto_20220204_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_num', models.CharField(max_length=200)),
                ('question_cla', models.CharField(max_length=200)),
                ('question_dif', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoSave',
        ),
    ]
