# Generated by Django 4.0.1 on 2022-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0006_questionchar_delete_videosave'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='2022년-02월-05일-18시-42분-26초', max_length=200)),
                ('interview_video', models.FileField(upload_to='%Y_%m_%d')),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
