# Generated by Django 4.0.2 on 2022-02-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0008_alter_interviewstorage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstorage',
            name='subject',
            field=models.CharField(default='2022년-02월-07일-11시-00분-57초', max_length=200),
        ),
    ]
