# Generated by Django 4.0.2 on 2022-02-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiotest', '0009_alter_interviewstorage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewStorage',
        ),
    ]
